### ISSUE TITLE
Jar Jar Boss

### ISSUE THREAD

**Issue by LcorpOfficial** [LcorpOfficial/LCC-Minecraft-Server#30]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
Jar Jar Binks inspired boss with... "big boomers"
**Describe alternatives you've considered**
explosive dragon fireballs, or heart of the sea based projectile.
**Provide a link to the plugin or reference to your suggestion**
mythicmobs boss
**Additional context notes**
per Jawa_Juice

**Comment by SevenCen** [comment]
Now
