### ISSUE TITLE
*** URGENT ***  Delete all tickets

### ISSUE THREAD

**Issue by maksic87** [LcorpOfficial/LCC-Minecraft-Server#35]
**Is your feature request related to a problem? Please describe.**
Yes, tickets are just dumb, do not listen to the community.

**Describe the solution you'd like**
Just yeet them.

**Describe alternatives you've considered**
Deleting, annihilating, destroying, nullifying....

**Provide a link to the plugin or reference to your suggestion**
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2FEnjoli-YEEET-BUTTON%2Fdp%2FB078M663HX&psig=AOvVaw39OeSHimc14b5oYR8QToFC&ust=1614296703172000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMCmj4Dag-8CFQAAAAAdAAAAABAD

**Additional context notes**
Just do it.

**Comment by LcorpOfficial** [comment]
note - Provide looting X enchantment @Nine-JuanJuan
