### ISSUE TITLE
Weird Spell Caster problem

### ISSUE THREAD

**Issue by CrispyCreeper1** [LcorpOfficial/LCC-Minecraft-Server#37]
When the spell caster casts a spell it shows mob.name instead of the name spellcaster could be a one off problem

**To Reproduce**
1. find spell caster and let it cast a spell
2.
3.
4.

**Expected behavior**
chat will say "mob.name begins casting a spell"

**Screenshots**
![2021-02-26_17 26 14](https://user-images.githubusercontent.com/79668601/109334118-306f7c80-7858-11eb-8d4d-e6d481ce2030.png)

**Minecraft Info (please complete the following information):**
 - Client: Vanilla
 - Version: 1.16.4
 - Mods (if any): optifine

**Additional context notes**

**Comment by LcorpOfficial** [comment]
replaced legacy placeholder `$boss` with `<mob.name><&co>` in Wizard's Config. Also polished the text formatting.
```
- message{m="<mob.name><&co> begins casting a spell."} @PIR{r=15}
- message{m="$boss &ebegins casting a spell."} @PIR{r=20}
```
