### ISSUE TITLE
Getting PVP off

### ISSUE THREAD

**Issue by maksic87** [LcorpOfficial/LCC-Minecraft-Server#38]
**Is your feature request related to a problem? Please describe.**
I am being PK'd by a player constantly. LCorp Official is familiar with the player.

**Describe the solution you'd like**
Disable PVP if possible or give me an option of removing the bully.

**Describe alternatives you've considered**
Stop interacting with players / Stop playing on LCorp City

**Provide a link to the plugin or reference to your suggestion**
Admin Blade.

**Additional context notes**
The bully is being aggressive without any reason and keeps killing me whenever he has a chance. I do not fight back. Also insulting without any reasons.

**Comment by Nine-JuanJuan** [comment]
Your suggestion has been acknowledged. Will be discussed.

**Comment by maksic87** [comment]
Thanks. Let me know. Since I will not play anymore on your server until this is resolved. Thanks.
