### ISSUE TITLE
Adding to speaker playlist for Shroom Kingdom

### ISSUE THREAD

**Issue by maksic87** [LcorpOfficial/LCC-Minecraft-Server#40]
**Is your feature request related to a problem? Please describe.**
Yes, I would need new songs added to the Shrom Kingdom playlist. (shrom islands that serve as my science facility)

**Describe the solution you'd like**
Please add the following, leave the ones already there is possible (height up to 200 if possible):

https://youtu.be/Jxbu80okI_U
https://youtu.be/mDFBTdToRmw
https://youtu.be/1t_sMynan_k
https://youtu.be/ADlGkXAz1D0
https://youtu.be/VfGRcl25qHg
https://youtu.be/jf0KciXneFk
https://youtu.be/wFAHXbZAojo
https://youtu.be/QrU1hZxSEXQ
https://youtu.be/SsFI40bXROs

**Describe alternatives you've considered**
Listening to Youtube while playing 🗡️ 

**Provide a link to the plugin or reference to your suggestion**
**LeAdminBoomBoxes**

**Additional context notes**
Not really I literally need songs added to a speaker 👯‍♂️

**Comment by LcorpOfficial** [comment]
Completed.
