### ISSUE TITLE
Bastard Blade, Bastard Wings and Bastard Bow - The Unholy Trinity set

### ISSUE THREAD

**Issue by maksic87** [LcorpOfficial/LCC-Minecraft-Server#43]
**Is your feature request related to a problem? Please describe.**
No, it is just a fun and dangerous set of items.

**Describe the solution you'd like**

**Bastard Wings** - Elytra that mends itself by draining the hitpoints of the player. Has a good unbreaking value and armour value to level up the things.

**Bastard Bow** - Infinity Bow that can be mended and Boosted by using hitpoints of the Player. Boost gives more power to it up to power 15 and mending works the same as the Wings one but can only be done if the player has the Unholy Trinity (all 3 items).

**Bastard Blade** - A blade of a true sadist. Use your HP to raise its sharpness up to 30 and drain half of your lifecap. Also increases speed and regen. Can be mended using HP if you have the Unholy Trinity.

**Describe alternatives you've considered**
Whining about the items to Corp until he makes them. 

**Provide a link to the plugin or reference to your suggestion**
It is all in my head. Dark web, you would not like it.

**Additional context notes**
The trifecta would be an item set that you literally need to die to get. Also the idea giver (me) gets one set for the idea.

**Comment by LcorpOfficial** [comment]
self note: will likely use attribute system instead of enchant (sharpness vs attack base damage attribute) for Sword.

**Comment by maksic87** [comment]
All items should have an option for Vanilla enchants if possible and the unbreaking attribute - Meaning that you can wear them down but cannot destroy them by using them, if possible.

**Comment by maksic87** [comment]
Regular Mending is not applicable to items. Also regular Sharpness and Power are not applicable if used in the original design.

**Comment by LcorpOfficial** [comment]
hmmm. perhaps using a custom mechanic for life force to be used as mana, or could use ammo of sorts for the ability. if it is low on ammo or mana it would dynamically be weaker or something. not sure, would have to look into possibilities.

**Comment by maksic87** [comment]
Anything new :D Do you need any help with this? I am available :D

**Comment by LcorpOfficial** [comment]
initial code made, item association and basic skills laid out
