### ISSUE TITLE
open shulkers without placing them

### ISSUE THREAD

**Issue by xanderstuff** [LcorpOfficial/LCC-Minecraft-Server#54]
be able to right click shulkers while holding in hand to open them, without needing to place them

**Comment by LcorpOfficial** [comment]
will be giving a test run on the test env. Good idea here.
plugin concept to test:
https://www.spigotmc.org/resources/shulker-backpacks-1-13-1-16.67466/

**Comment by Nine-JuanJuan** [comment]
Plugin has been implemented.
