### ISSUE TITLE
money drops from mobs

### ISSUE THREAD

**Issue by xanderstuff** [LcorpOfficial/LCC-Minecraft-Server#55]
I would kinda like mobs to drop coins/gold or some other currency as an item, rather than money going directly into your balance. It would also be preferable for the currency item to make a nice sound when it is collected. 
The reason being collecting items in an rpg can be really fun, and dropping a currency item is a bit more realistic/physical.

**Comment by LcorpOfficial** [comment]
notes to self:

consider implications of physical currency implementation for loot items. perhaps tie-in loot currency with bounty shop?

also consider possibility for sounds to be played when currency is given upon defeating a mob? looking into options for this.

**Comment by xanderstuff** [comment]
oh, and preferably a mob could drop a random amount of currency items, say 1-3, just to really hone-in on that hack and slash item-collecting goodness.

**Comment by LcorpOfficial** [comment]
currently, they drop a range directly, would just convert that to items. i'm still concerned with the idea of making a physical representation of money however, as it would need different ones to scale, and could end up confusing to players that have no idea how to convert them to money without instruction. i'll keep knocking this around.

**Comment by xanderstuff** [comment]
it doesn't necessarily have to be a physical item to go in inventories. I think something that just gets left in the place where mobs are killed (or other scenarios??) is what we're after. Once the player walks over it, it could trigger something to go directly to the player's balance.

**Comment by LcorpOfficial** [comment]
ah, like a dummy item that upon pickup converts into a balance amount. That gives me a bit more options.

**Comment by xanderstuff** [comment]
not sure on the best way to implement this, but one idea is using a real minecraft item, but when a player picks it up in their inventory, it gets immediately taken away and added to their balance. Of course, there could be issues with this idea as you previously mentioned.

another idea could be to use fancy entities to render this "dropped loot", but trigger collection into their balance on hitbox collision, or perhaps when a player gets in range of the "loot entity" (say, 1-2 block distance)

Interestingly, this idea is EXACTLY how minecraft xp orbs behave... hmmm

**Comment by xanderstuff** [comment]
oh, and I suppose automatic despawning after a minute or a few would be prudent to prevent loot buildup issues

**Comment by LcorpOfficial** [comment]
ideally, I could do an item that functions as a mythic mob and it runs a skill when a player is within 1 block of it that gives the loot balance, then despawns. stationary mob with playerhead that looks like a moneybag. it can also kill itself (despawn) after a certain amount of time after spawning. it'd be easy to make them spawn after killing a mob that would drop it, and i can make different variations for different ranges of cash. even use different textures to differentiate. On top of that, they could even be used as world loot by having randomspawn parameters in the wild, or be used during events for stuff.

**Comment by LcorpOfficial** [comment]
unsatisfactory performance and immersion breaking when tested. Also can be a bit confusingly redundant in implementation. Closing issue but will keep ideas like this in mind for the future.
