### ISSUE TITLE
README.md says server is 1.16.X, but is actually 1.16.4/1.16.5

### ISSUE THREAD

**Issue by xanderstuff** [LcorpOfficial/LCC-Minecraft-Server#56]
**Describe the bug**
README.md says the server version is 1.16.X, but is actually 1.16.4/1.16.5

![image](https://user-images.githubusercontent.com/68503800/114302547-2cf22680-9a8f-11eb-8dd7-2c753f799505.png)

**Expected behavior**
state only accepted minecraft versions (1.16.4/1.16.5)

**Comment by LcorpOfficial** [comment]
at the time, server ran 1.16.2 with ViaBackwards. this is fixed on the site/github now.
