### ISSUE TITLE
SCP 4335 Boss

### ISSUE THREAD

**Issue by LcorpOfficial** [LcorpOfficial/LCC-Minecraft-Server#59]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
SCP 4335 Inspired boss
**Describe alternatives you've considered**
SCP 4335 related combat or herobrine lore integration
**Provide a link to the plugin or reference to your suggestion**
https://youtu.be/D7-egKdS0-0
**Additional context notes**
https://scp-wiki.wikidot.com/scp-4335

![image](https://user-images.githubusercontent.com/73314328/116989128-54f43480-ac9f-11eb-9b61-6dadda5be29e.png)

**Comment by SevenCen** [comment]
Pp
