### ISSUE TITLE
Wall art corruption

### ISSUE THREAD

**Issue by maksic87** [LcorpOfficial/LCC-Minecraft-Server#61]
**Describe the bug**
Wall art in Mayor house Cobblewood is a casino map art

**To Reproduce**
1. Open the door to the house
2. Walk in
3.Look at the map art
4.Notice the coruption

**Expected behavior**
Replace with pictures of bees and birbs

**Screenshots**

**Minecraft Info (please complete the following information):**
 - Client: MultiMC
 - Version:1.16.5
 - Mods (if any):

**Additional context notes**

**Comment by LcorpOfficial** [comment]
removed. 1 free voucher to replace map art is available for @KailaniWaves if she wishes to repair.
