### ISSUE TITLE
Audio Client Sources from SoundCloud need replaced with self host

### ISSUE THREAD

**Issue by LcorpOfficial** [LcorpOfficial/LCC-Minecraft-Server#65]
**Describe the bug**
Soundcloud link-based sources are not able to be played with OA Client due to 3rd-party API flags.

**To Reproduce**
1. go to a place
2. open audio client
3. audio is silent from SC sources
4. (op) recieve error in chat.

**Expected behavior**
tunes.

**Minecraft Info (please complete the following information):**
 - Client: Fabric 
 - Version: 1.17.1
 - Mods (if any): N/A

**Additional context notes**
sources need to be converted to a self-hosted file on LCC Media Server, then URL needs updated in OA config.

**Comment by SevenCen** [comment]
Pp
