### ISSUE TITLE
Item Pedestal

### ISSUE THREAD

**Issue by maksic87** [LcorpOfficial/LCC-Minecraft-Server#70]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

A one slot container capable of displaying a 3d model of the item inside would be used to show of prized possessions. Should only be purchasable or craftable with a barrel netherite scraps and an end rod.

**Comment by LcorpOfficial** [comment]
this is doable manually via invis item frames and glass blocks or similar, letting you completely customize how you display your item. see /pw museum for examples. can be placed against walls or surfaces.
