### ISSUE TITLE
Adminuim Gem and Shards

### ISSUE THREAD

**Issue by maksic87** [LcorpOfficial/LCC-Minecraft-Server#71]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

A craftable item that can either be crafted or socketed into armour. The item is a blue Gem and it is crafted from shards obtainable from either completing quests or beating low tier bosses or as a random drop.

Item would give the wearer some energy and hunger regen, not to much but just enough to keep you alive during long expeditions or big builds. Item could be crafted from 9 shards or 8 shards and an eye of ender. 

_Lore: The Adminium gem came to be during the past era, it was an item granted to the LCC citizens to keep them safe and nurtured during the Demon Realm invasion and now it can be found in shards across Lcorp City. You can craft it and it will keep you fed and full of energy given enough time._

**Comment by maksic87** [comment]
Other uses: Can be used to buff the whole party and that in return destroys the gem [sends it back to the Adminium cluster]. Boost gives enhanced health, strength, speed and regen for 1 hour. It can be used on a party of 5 and will stay applied for an hour even if one member perishes, the effect is not removed by death.

**Comment by maksic87** [comment]
Crafting recipe should be decided on but I would go with either 8 shards and eye of ender or 8 shards and an End Crystal.

**Comment by LcorpOfficial** [comment]
like the idea of either heart of the sea/end crystal surrounded by shards. 

also like the idea that it is consumed on use, and gives a radius buff around the user for a specified time period. good for healer-type players or support in raid squads

**Comment by LcorpOfficial** [comment]
currently implemented to make flight potions, and elytra. will have consume usage later.
