### ISSUE TITLE
[SUGGESTION] Dragon's Lung

### ISSUE THREAD

**Issue by timo84746454** [LcorpOfficial/LCC-Minecraft-Server#74]
### Is your feature request related to a problem?

No

### Please describe.

A Dragon Head that allows the player to breathe the dragon's breath, dealing magic dmg.  Primary ATK is firing a dragon's breath ball, Secondary is a rapid succession of dragons breath(rapid fire, 10 or more), at the cost of 60+ energy.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Provide a link to the plugin or reference to your suggestion. (If applicable)

N/A

### Additional Notes

You can make the Dragon's Breath with Dragons breath, a Dragon Head, and ender pearls. Add a minor HP boost?

**Comment by LcorpOfficial** [comment]
would likely become a possible ender knight drop, will not make mythical-tier items like this craftable. 

 Notes:
• fireball = onswing - 14 en
• flamethrower breath = onuse - 1 en/usage/repeating

**Comment by LcorpOfficial** [comment]
finished, drop available from Ender Knight
