### ISSUE TITLE
[SUGGESTION] Mobcap Belt

### ISSUE THREAD

**Issue by timo84746454** [LcorpOfficial/LCC-Minecraft-Server#75]
### Is your feature request related to a problem?

No

### Please describe.

Similar to that of the Key Chain, you have a Mobcap belt, used to hold various mobcaps.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Provide a link to the plugin or reference to your suggestion. (If applicable)

N/A

### Additional Notes

Can be made with 3 mobcaps.  Holds 9 different Mobcaps.

**Comment by LcorpOfficial** [comment]
Shulker Packs handle this, they can be named as well as colored.
