### ISSUE TITLE
Genshin Music for Mondstadt

### ISSUE THREAD

**Issue by CrispyCreeper1** [LcorpOfficial/LCC-Minecraft-Server#79]
### Speaker Voucher?

- [X] I have Purchased a Speaker Voucher.

### Tracks

Day
https://www.youtube.com/watch?v=JpxBvbKzavI
https://www.youtube.com/watch?v=c3Gi1rydctY
https://www.youtube.com/watch?v=3sVSOK2VTyY

Night
https://www.youtube.com/watch?v=6AG7TMFj8Wk
https://www.youtube.com/watch?v=NyhG7-LjveU
https://www.youtube.com/watch?v=aYfZHKiI444

### Name

Mondstadt

### Audio Region Rules

- [X] Allow Guards and Citizens to spawn, like a town or city.
- [X] Prevent specific mob types from spawning at all.
- [X] Prevent PVP in the region.
- [ ] Allow for KeepInventory (disable death backpacks) in your region if it's an area meant to be used for combat.
- [X] give (1) Potion Effect.
- [X] Set a welcome message.

### Potion Effect

Speed 2

### Welcome Message

Mondstadt - The City of Wind and Song

**Comment by LcorpOfficial** [comment]
Completed
