### ISSUE TITLE
[SUGGESTION] more hats/hat variations 

### ISSUE THREAD

**Issue by SevenCen** [LcorpOfficial/LCC-Minecraft-Server#80]
### Is your feature request related to a problem?

No

### Please describe.

i want hats

### Describe the solution you'd like

halo/horn variants, sunhat(s), tiara/crown variants, kitsune masks

### Provide a link to the plugin or reference to your suggestion. (If applicable)

https://www.pinterest.com/pin/709879959998448452/ horns
https://www.pinterest.com/pin/596656650608183027/ halos
https://www.pinterest.com/pin/563794447095892108/ kitsune mask

**Comment by LcorpOfficial** [comment]
can be done, consider it on the to-do list.
